apiVersion: skaffold/v4beta6
kind: Config
build:
  platforms:
    - linux/amd64
  artifacts:
    - image: cairo-auth-proxy
      context: ./proxy
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      # - ./k8s
      - ./proxy/k8s
