apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxy-cert
spec:
  secretName: proxy-tls
  dnsNames:
    - proxy.test
  issuerRef:
    name: selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
spec:
  secretName: example-tls
  dnsNames:
    - example.test
  issuerRef:
    name: selfsigned-issuer
